// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrK6edIxPnTk-DaysNjkzDpA16lscpMNU',
    appId: '1:597791098480:web:417ef5af35086c9c3dd6b5',
    messagingSenderId: '597791098480',
    projectId: 'qqqq-eb471',
    authDomain: 'qqqq-eb471.firebaseapp.com',
    databaseURL: 'https://qqqq-eb471-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qqqq-eb471.firebasestorage.app',
    measurementId: 'G-XGK3GTLHND',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrK6edIxPnTk-DaysNjkzDpA16lscpMNU',
    appId: '1:597791098480:web:f6982220d5767bab3dd6b5',
    messagingSenderId: '597791098480',
    projectId: 'qqqq-eb471',
    authDomain: 'qqqq-eb471.firebaseapp.com',
    databaseURL: 'https://qqqq-eb471-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qqqq-eb471.firebasestorage.app',
    measurementId: 'G-EPJV1EQJ0C',
  );
}
